config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/home", to: "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/register", to: "users#new"
  post "/register", to: "users#create"
  resources :users
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  scope :order_by_name, ->(sort_order){order("LOWER(name) #{sort_order}")}
  VALID_EMAIL_REGEX = /\A[\w\-.+]+@[a-z\-\d.]+\.[a-z]+\z/i.freeze
  before_save{email.downcase!}
  validates :name, presence: true,
            length: {maximum: Settings.max_length.name_50}
  validates :email, presence: true,
            length: {maximum: Settings.max_length.email_255},
                    format: {with: VALID_EMAIL_REGEX},
                    uniqueness: {case_sensitive: false}
  validates :password, presence: true,
            length: {minimum: Settings.max_length.password_8}
  has_secure_password
  attr_accessor :remember_token

  class << self
    def new_token
      SecureRandom.urlsafe_base64
    end

    def digest string
      cost = if ActiveModel::SecurePassword.min_cost
               BCrypt::Engine::MIN_COST
             else
               BCrypt::Engine.cost
             end
      BCrypt::Password.create string, cost: cost
    end
  end

  def remember_me
    self.remember_token = User.new_token
    update_column :remember_digest, User.digest(remember_token)
  end

  def authenticated? remember_token
    BCrypt::Password.new(remember_digest).is_password? remember_token
  end
end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController
  def edit
    user = User.find_by email: params[:email]
    if user && !user.activated? && user.authenticated?(:activation, params[:id])
      user.update_attribute :activated_at, Time.zone.now
      flash[:success] = t "account_activated"
      redirect_to login_url
    else
      flash[:danger] = t "invalid_activation_link"
      redirect_to root_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  protect_from_forgery with: :exception
  include SessionsHelper

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    {locale: I18n.locale}
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    session_params = params[:session]
    user = User.find_by email: session_params[:email].downcase
    if user&.authenticate(session_params[:password])
      log_in user, session_params[:remember_me]
      flash[:success] = t "welcome_logged_in_message_html", username: user.name
      redirect_back_or user
    else
      flash.now[:danger] = t "email_or_password_incorrect"
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in, only: %i(index edit update destroy)
  before_action :same_user, only: %i(edit update)
  before_action :admin_logged_in, :not_same_user, only: :destroy
  include SessionsHelper

  def index
    @users = User.order_by_name(:ASC).paginate(page: params[:page],
                          per_page: Settings.will_pagination.per_page_10)
  end

  def edit
    load_user_or_redirect
  end

  def show
    load_user_or_redirect
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = t "user_created_html", username: @user.name
      redirect_to login_url
    else
      render :new
    end
  end

  def update
    load_user_or_redirect
    if update_success?
      flash[:success] = t "user_updated_html", username: @user.name
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    load_user_or_redirect
    if @user&.destroy
      flash[:success] = t "user_deleted_html", username: @user.name
    else
      flash[:warning] = t "user_deletion_failed_html", username: @user.name
    end
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  def logged_in
    return if logged_in?

    save_back_url
    flash[:danger] = t "login_first"
    redirect_to login_url
  end

  def load_user_or_redirect
    @user = User.find_by id: params[:id]
    return if @user.present?

    flash[:danger] = t "user_not_found"
    redirect_to users_url
  end

  def update_success?
    params = user_params
    @user.update_attribute(:name, params[:name]) &&
      @user.update_attribute(:email, params[:email])
  end

  def same_user
    load_user_or_redirect
    return if @user == current_user

    flash[:danger] = t "must_same_user_html", username: @user.name
    redirect_to users_url
  end

  def not_same_user
    load_user_or_redirect
    return unless @user == current_user

    flash[:danger] = t "can_not_delete_self"
    redirect_to users_url
  end

  def admin_logged_in
    return if current_user.is_admin

    flash[:danger] = t "must_be_admin"
    redirect_to users_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = t "app_name"
    page_title.empty? ? base_title : "#{page_title} | #{base_title}"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user, remember_me
    # saves user id to client's session cookie
    session[:user_id] = user.id
    remember user if remember_me == "1"
  end

  def remember user
    user.remember_me
    cookies.permanent[:remember_token] = user.remember_token
    cookies.permanent.signed[:user_id] = user.id
  end

  def current_user
    # gets current user info
    # @current_user ||= User.find_by id: session[:user_id]
    if (user_id = session[:user_id])
      @current_user ||= User.find_by id: user_id
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by id: user_id
      if user&.authenticated?(cookies[:remember_token])
        log_in user, false
        @current_user = user
      end
    end
  end

  def logged_in?
    # shorthand for checking if current user is present
    current_user.present?
  end

  def log_out
    session.delete(:user_id)
    cookies.delete :user_id if cookies.signed[:user_id]
    @current_user = nil
  end

  def save_back_url
    session[:back_url] = request.original_url if request.get?
  end

  def redirect_back_or default
    redirect_to session[:back_url] || default
    session.delete :back_url
  end
end

app/helpers/users_helper.rb
module UsersHelper
  include SessionsHelper
  def gravatar_for user
    gravatar_id = Digest::MD5.hexdigest user.email
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end

  def should_show_delete? user
    current_user.is_admin && current_user != user
  end
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar fixed-top navbar-expand navbar-inverse">
    <div class="container">
      <%= link_to t("app_name"), root_path, class: "navbar-header navbar-brand" %>
      <ul class="nav navbar-nav navbar-right">
        <li class="nav-item"><%= link_to t(".home"), home_path %></li>
        <li class="nav-item"><%= link_to t(".help"), help_path %></li>
        <% if logged_in? %>
          <li class="nav-item"><%= link_to t(".users"), users_path %></li>
          <li class="dropdown">
            <%= link_to "#", class: "dropdown-toggle", "data-toggle": "dropdown" do %>
              <%= t ".account" %>
              <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t(".profile"), current_user %></li>
              <li><%= link_to t(".settings"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li> <%= link_to t(".logout"), logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to t(".login"), login_path %></li>
          <li class="nav-item"><%= link_to t(".register"), register_path %></li>
        <% end %>
        <% I18n.available_locales.each do |lang| %>
          <li class="nav-item"><%= link_to lang.to_s.upcase, (request.path+"?locale=#{lang}") %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body class="bg-3ec">
    <%= render "layouts/header" %>
    <div class="sticky-top">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <div class="container">
            <%= message.html_safe %>
          </div>
        </div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user&.errors&.any? %>
  <div id="error_explanation" class="row">
    <div class="alert alert-danger">
      <%= t ".please_resolve_errors", count: @user.errors.count %>:
      <ol>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ol>
    </div>
  </div>
<% end %>

app/views/static_pages/help.html.erb
<% provide :title, t(".title") %>
<div class="jumbotron center">
  <div class="container">
    <h1><%= t ".h1_html" %></h1>
    <p><%= t ".para_html" %>
    </p>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="jumbotron center">
  <div class="container">
    <h1><%= t ".h1_html" %></h1>
    <p><%= t ".para_html" %></p>
    <%= link_to t(".sign_up"), register_path, class: "btn btn-primary btn-lg" %>
  </div>
</div>

app/views/users/edit.html.erb
<% provide :title, t("layouts.header.settings") %>
<div class="container">
  <h1 class="center"><%= t "layouts.header.settings" %></h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render "shared/error_messages", object: @user %>
      <%= form_for @user do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: "form-control" %>
        </div>
        <div>
          <%= button_tag t("reset_text"), type:"reset", class: "btn btn-default col-sm-6" %>
          <%= f.submit t(".submit"), class: "btn btn-primary col-sm-6" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide :title, t("layouts.header.users") %>
<div class="container">
  <h1 class="center"><%= t "layouts.header.users" %></h1>
  <div class="row">
    <%= will_paginate %>
    <ul class="list-unstyled col-md-6 col-md-offset-3">
      <% @users.each do |user| %>
        <li class="row">
          <div class="col-sm-2">
            <%= gravatar_for user %>
          </div>
          <div class="col-sm-10">
            <p><%= link_to user.name, user %></p>
            <% if should_show_delete? user %>
              <p><%= link_to t(".delete_user"), user, method: :delete, class: "text-danger" %></p>
            <% end %>
          </div>
        </li>
      <% end %>
    </ul>
    <%= will_paginate %>
  </div>
</div>

app/views/users/new.html.erb
<% provide :title, t(".register") %>
<div class="container">
  <h1 class="center"><%= t ".register" %></h1>
  <%= render 'shared/error_messages' %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for @user, url: register_path do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation, t(".confirmation") %>
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
        <%= f.submit t(".submit"), class: "btn btn-primary center-block" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<div class="container">
  <aside class="row">
    <section>
      <div class="col-sm-2">
        <%= gravatar_for @user %>
      </div>
      <div class="col">
        <h1>
          <%= @user.name %>
        </h1>
        <h1>
          <%= @user.email %>
        </h1>
      </div>
    </section>
  </aside>
</div>